# Generated by Django 4.1.3 on 2023-02-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifyrecord_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=225, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gexing',
            field=models.CharField(blank=True, default='', max_length=125, verbose_name='个性签名'),
        ),
    ]
