# Generated by Django 4.1.3 on 2023-02-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_desc_userprofile_gexing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('female', '女'), ('male', '男')], default='male', max_length=6, verbose_name='性别'),
        ),
    ]
